TRPManagement/TRPManagement/Controllers/ChannelController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.NetworkInformation;
using System.Web;
using System.Web.Mvc;
using TRPManagement.DTOs;
using TRPManagement.EF;
using TRPManagement.Models;

namespace TRPManagement.Controllers
{
    public class ChannelController : Controller
    {
        MidPracticeTaskEntities db = new MidPracticeTaskEntities();
        
        public ActionResult List()
        {
            var channel = db.Channels.ToList();
            ViewBag.Channels = channel;
            return View(ConvertDTO.Convert(channel));
        }

        [HttpGet]
        public ActionResult FilterByChannel(int ChannelId)
        {
            var channel = (from c in db.Channels
                           where c.ChannelId == ChannelId
                           select c).FirstOrDefault();

            var programs = (from p in db.Programs
                            where p.ChannelId == ChannelId
                            select p).ToList();

            ViewBag.ChannelName = channel.ChannelName;
            return View(ConvertDTO.Convert(programs));
        }









        [HttpGet]
        public ActionResult Create()
        {
            return View(new Channel());
        }

        [HttpPost]
        public ActionResult Create(ChannelDTO channelDTO)
        {
            bool isChannelNameExists = (from c in db.Channels
                                        where c.ChannelName == channelDTO.ChannelName
                                        select c).Any();

            if (isChannelNameExists)
            {
                ModelState.AddModelError("ChannelName", "Channel name must be unique.");
                return View(channelDTO); 
            }

            if (ModelState.IsValid)
            {
                var channel = ConvertDTO.Convert(channelDTO);
                db.Channels.Add(channel);
                db.SaveChanges();
                TempData["msg"] = "Channel created successfully!";
                return RedirectToAction("List");
            }

            return View(channelDTO);
        }


        [HttpGet]
        public ActionResult Edit(int id)
        {
            var channel = db.Channels.Find(id);
            return View(channel);
        }
        [HttpPost]
        public ActionResult Edit(ChannelDTO channelDTO)
        {
            if (ModelState.IsValid)
            {
                var channel = db.Channels.Find(channelDTO.ChannelId);
                channel.ChannelName = channelDTO.ChannelName;
                channel.EstablishedYear = channelDTO.EstablishedYear;
                channel.Country = channelDTO.Country;
                db.SaveChanges();
                TempData["msg"] = "Channel updated successfully!";
                return RedirectToAction("List");
            }
            return View(channelDTO);

        }

        [HttpGet]
        public ActionResult Delete(int id)
        {
            var channel = db.Channels.Find(id);
            var programs = (from p in db.Programs
                            where p.ChannelId == id
                            select p).ToList();
            ViewBag.plist = programs;
            return View(ConvertDTO.Convert(channel));
        }
        [HttpPost]
        public ActionResult Delete(ChannelDTO channel, string reply)
        {
            if (reply=="Yes") { 
            var check_programs = (from p in db.Programs
                                  where p.ChannelId == channel.ChannelId
                                  select p).ToList();
            if (check_programs.Count > 0)
            {
                TempData["msg"] = "This channel has programs. Please delete the programs first!";
                return RedirectToAction("List");
            }
            else
            {
                var ch = db.Channels.Find(channel.ChannelId);
                db.Channels.Remove(ch);
                db.SaveChanges();
                TempData["msg"] = "Channel deleted successfully!";
                return RedirectToAction("List");
            }
        }
            return RedirectToAction("List");

        }

    }
}

TRPManagement/TRPManagement/Controllers/ProgramController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TRPManagement.DTOs;
using TRPManagement.EF;
using TRPManagement.Models;

namespace TRPManagement.Controllers
{
    public class ProgramController : Controller
    {
        MidPracticeTaskEntities db = new MidPracticeTaskEntities();
        
        //[HttpGet]
        //public ActionResult Create(int channelId) //this one is for create from the channel list
        //{   

        //    var channelName = (from c in db.Channels
        //                       where c.ChannelId == channelId
        //                       select c.ChannelName).FirstOrDefault();

        //    ViewBag.ChannelId = channelId;
        //    ViewBag.ChannelName = channelName;
        //    return View();
        //}

        //[HttpPost]
        //public ActionResult Create(ProgramDTO programDTO) //this one is for create from the channel list
        //{
        //    var program = ConvertDTO.Convert(programDTO);
        //    db.Programs.Add(program);
        //    db.SaveChanges();
        //    TempData["msg"] = "Program added successfully!";
        //    return RedirectToAction("List", "Channel");
        //}

        [HttpGet]
        public ActionResult CreateProgram()
        {
            ViewBag.channels = ConvertDTO.Convert(db.Channels.ToList());
            return View(new Program());
        }

        [HttpPost]
        public ActionResult CreateProgram(ProgramDTO program)
        {
            if (ModelState.IsValid)
            {
                db.Programs.Add(ConvertDTO.Convert(program));
                db.SaveChanges();
                TempData["msg"] = "Program added successfully!";
                return RedirectToAction("ProgramList");
            }

            ViewBag.channels = ConvertDTO.Convert(db.Channels.ToList()); //onek pera dise
            return View(program);
        }



        [HttpGet]
        public ActionResult EditProgram(int id)
        {
            var program = db.Programs.Find(id);
            ViewBag.channels = ConvertDTO.Convert(db.Channels.ToList());
            ViewBag.Channel_Name = db.Channels.Find(program.ChannelId);
            return View(ConvertDTO.Convert(program));
        }

        [HttpPost]
        public ActionResult EditProgram(ProgramDTO programDTO)
        {
            var program = db.Programs.Find(programDTO.ProgramId);
            program.ProgramName = programDTO.ProgramName;
            program.TRPScore = programDTO.TRPScore;
            program.ChannelId = programDTO.ChannelId;
            program.AirTime = programDTO.AirTime;
            db.SaveChanges();
            TempData["msg"] = "Program updated successfully!";
            return RedirectToAction("ProgramList");
        }

        [HttpGet]
        public ActionResult DeleteProgram(int id)
        {
            var program = db.Programs.Find(id);
            ViewBag.Channel_Name = db.Channels.Find(program.ChannelId);
            return View(ConvertDTO.Convert(program));
        }

        [HttpPost]
        public ActionResult DeleteProgram(ProgramDTO program, string reply)
        {
            var program_find = db.Programs.Find(program.ProgramId);
            if (reply.Equals("Yes"))
            {
                db.Programs.Remove(program_find);
                db.SaveChanges();
                TempData["msg"] = "Program deleted successfully!";
                return RedirectToAction("ProgramList");
            }
            TempData["msg"] = "Program deleted unsuccessfull!";
            return RedirectToAction("ProgramList");
        }

        public ActionResult ProgramList()
        {
            var channel = db.Channels.ToList();
            var program = db.Programs.ToList();
            ViewBag.Channels = channel;
            return View(channel);
        }

        public ActionResult Search(string searchTerm)
        {
            var programs = from p in db.Programs
                           select p;

            // Check if searchTerm is numeric (for TRP score)
            if (decimal.TryParse(searchTerm, out decimal trpScore))
            {
                // If it's a valid TRP score, filter by TRP score
                programs = from p in programs
                           where p.TRPScore == trpScore
                           select p;
            }
            else if (!string.IsNullOrEmpty(searchTerm))
            {
                // If it's not a number, assume it's a program name
                programs = from p in programs
                           where p.ProgramName.Contains(searchTerm)
                           select p;
            }

            return View(ConvertDTO.Convert(programs.ToList())); // Assuming ConvertDTO is used for converting entities to DTOs
        }


    }
}

TRPManagement/TRPManagement/Views/Channel/ChannelList.cshtml
@{
    ViewBag.Title = "ChannelList";
}

<h4 class="text-center">List of Available Channels</h4>
@if (TempData["msg"] != null)
{
    <div class="alert alert-success">
        @TempData["msg"]
    </div>
}

<table class="table table-bordered">
    <tr>
        <th>Channel ID</th>
        <th>Channel Name</th>
        <th>Establisher Year</th>
        <th>Country</th>
        <th>Actions</th>
    </tr>
    @foreach(var item in Model)
            {
                <tr>
                    <td>@item.ChannelId</td>
                    <td>@item.ChannelName</td>
                    <td>@item.EstablishedYear</td>
                    <td>@item.Country</td>
                    <td>
                        <a href="/channel/EditChannel/@item.ChannelId" class="btn btn-warning">Edit</a>
                        <a href="/channel/DeleteChannel/@item.ChannelId" class="btn btn-danger">Delete</a>
                    </td>
                </tr>
            }
</table>
<div>
    <h5>Add More Channel </h5><a href="/channel/createchannel" class="btn btn-primary">Create</a>
    <a href="/program/programlist" class="btn btn-primary">Program</a>

</div>

TRPManagement/TRPManagement/Views/Channel/Create.cshtml
@{
    ViewBag.Title = "Create";
}

<h4>Create Channel</h4>

<form method="post">
    Channel Name: <input type="text" name="ChannelName" value="@Model.ChannelName" class="form-control" /><br />
    <span class="text-danger">@Html.ValidationMessage("ChannelName")</span>
    Established Year: <input type="number" name="EstablishedYear" value="@Model.EstablishedYear" class="form-control" /><br />
    <span class="text-danger">@Html.ValidationMessage("EstablishedYear")</span>
    Country: <input type="text" name="Country" value="@Model.Country" class="form-control" /><br />
    <span class="text-danger">@Html.ValidationMessage("Country")</span>
    <input type="submit" value="Create" class="btn btn-success" />
    <a href="/channel/list" class="btn btn-primary">Back</a>
</form>

TRPManagement/TRPManagement/Views/Channel/CreateChannel.cshtml
@{
    ViewBag.Title = "CreateChannel";
}

<h2>Create Channel</h2>

<div>
    <form method="post">

        <input type="text" name="ChannelName" placeholder="Channel Name" value="@Model.ChannelName" class="form-control" />
        <p class="text-danger">@Html.ValidationMessage("ChannelName")</p>
        <input type="number"  name="EstablishedYear" placeholder="Established Year" value="@Model.EstablishedYear" class="form-control" />
        <p class="text-danger">@Html.ValidationMessage("EstablishedYear")</p>
        <input type="text" name="Country" placeholder="Channel Country" value="@Model.Country" class="form-control" />
        <p class="text-danger">@Html.ValidationMessage("Country")</p>
        <input type="submit" value="Create" class="btn btn-success" />
        <a href="/channel/channellist" class="btn btn-danger">Back</a>
    </form>
</div>

TRPManagement/TRPManagement/Views/Channel/Delete.cshtml
@{
    ViewBag.Title = "Delete";
}

<h2>Delete Channel</h2>
@if (TempData["msg"] != null)
{
    <div class="alert alert-warning">
        @TempData["msg"]
    </div>
}
<form method="post">
    <table class="table table-bordered">
        <tr>
            <th colspan="4" class="text-center">@Model.ChannelName</th>
        </tr>
        <tr>
            <th>Program Id</th>
            <th>Program Name</th>
            <th>Air Time</th>
            <th>TRP</th>
        </tr>
        @foreach (var item in ViewBag.plist)
        {
            <tr>
                <td>@item.ProgramId</td>
                <td>@item.ProgramName</td>
                <td>@item.AirTime</td>
                <td>@item.TRPScore</td>
            </tr>
        }
    </table>
    <input type="hidden" name="ChannelId" value="@Model.ChannelId" />
    <input type="submit" value="Yes" class="btn btn-danger" name="reply" />
    <input type="submit" value="No" class="btn btn-warning" name="reply" />
</form>

TRPManagement/TRPManagement/Views/Channel/DeleteChannel.cshtml
@{
    ViewBag.Title = "DeleteChannel";
}

<h2>Delete Channel</h2>

<form method="post">

    <table class="table table-bordered">
        <tr>
            <th colspan="4" class="text-center">@Model.ChannelName</th>
        </tr>
        <tr>
            <th>Program ID</th>
            <th>Program Name</th>
            <th>Air Time</th>
            <th>TRP</th>
        </tr>
        @foreach (var item in ViewBag.Programs)
        {
            <tr>
                <td>@item.ProgramId</td>
                <td>@item.ProgramName</td>
                <td>@item.AirTime</td>
                <td>@item.TRPScore</td>
            </tr>
        }
    </table>

    <input type="hidden" name="ChannelId" value="@Model.ChannelId" />
    @if (ViewBag.Programs.Count > 0)
    {   
        <h6 class="text-danger text-center">This Channel contains programs already. You Cannot delete this Channel</h6>
        <input disabled type="submit" value="Yes" class="btn btn-danger" name="reply" />
    }
    else
    {
        <input type="submit" value="Yes" class="btn btn-danger" name="reply" />

    }
        <input type="submit" value="No" class="btn btn-success" name="reply" />
</form>

TRPManagement/TRPManagement/Views/Channel/Edit.cshtml
@{
    ViewBag.Title = "Edit";
}

<h4><u>Edit Existing Channel</u></h4>

<form method="post">
    <input type="hidden" name="ChannelId" value="@Model.ChannelId" />
    Channel Name: <input type="text" name="ChannelName" value="@Model.ChannelName" class="form-control" /><br />
    Established Year: <input type="number" min="1900" name="EstablishedYear" value="@Model.EstablishedYear" class="form-control" /><br />
    Country: <input type="text" name="Country" value="@Model.Country" class="form-control" /><br />
    <input type="submit" value="Update" class="btn btn-success" />
    <a href="/channel/list" class="btn btn-primary">Back</a>
</form>

TRPManagement/TRPManagement/Views/Channel/EditChannel.cshtml
@{
    ViewBag.Title = "EditChannel";
}

<h2>Edit Channel</h2>

<div>
    <form method="post">
        <input type="hidden" name="ChannelId" value="@Model.ChannelId" />
        <input type="text" name="ChannelName" placeholder="Channel Name" value="@Model.ChannelName" class="form-control" />
        <p class="text-danger">@Html.ValidationMessage("ChannelName")</p>
        <input type="number" name="EstablishedYear" placeholder="Established Year" value="@Model.EstablishedYear" class="form-control" />
        <p class="text-danger">@Html.ValidationMessage("EstablishedYear")</p>
        <input type="text" name="Country" placeholder="Channel Country" value="@Model.Country" class="form-control" />
        <p class="text-danger">@Html.ValidationMessage("Country")</p>
        <input type="submit" value="Update" class="btn btn-success" />
        <a href="/channel/channellist" class="btn btn-danger">Back</a>
    </form>
</div>

TRPManagement/TRPManagement/Views/Channel/FilterByChannel.cshtml
@{
    ViewBag.Title = "FilterByChannel";
}

<h2>Programs in @ViewBag.ChannelName</h2>

<table class="table table-bordered">

    <tr>
        <th>Program Name</th>
        <th>Trp Score</th>
        <th>Air Time</th>
    </tr>
    @foreach (var program in Model)
    {
        <tr>
            <td>@program.ProgramName</td>
            <td>@program.TRPScore</td>
            <td>@program.AirTime</td>
        </tr>
    }
</table>
<a href="/channel/list" class="btn btn-secondary">Back to Channels</a>

TRPManagement/TRPManagement/Views/Channel/List.cshtml
@{
    ViewBag.Title = "List";
}

<h2>List Of Available Channels</h2>
@if (TempData["msg"] != null)
{
    <div class="alert alert-success">
        @TempData["msg"]
    </div>
}

<h2>Filter Programs By Channel</h2>
<form method="get" action="/channel/filterbychannel">
    <label for="ChannelId">Select Channel:</label>
    <select name="ChannelId" id="ChannelId" class="form-control" onchange="this.form.submit()">
        <option value="">Select Channel</option>
        @foreach (var channel in ViewBag.Channels)
        {
            <option value="@channel.ChannelId">@channel.ChannelName</option>
        }
    </select>
</form>


<table class="table table-bordered">
    <tr>
        <th>Channel ID</th>
        <th>Channel Name</th>
        <th>Established Year</th>
        <th>Country</th>
        <th>Actions</th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>@item.ChannelId</td>
            <td>@item.ChannelName</td>
            <td>@item.EstablishedYear</td>
            <td>@item.Country</td>
            <td>
                <a href="/channel/edit/@item.ChannelId" class="btn btn-primary">Edit</a>
                <a href="/channel/delete/@item.ChannelId" class="btn btn-danger">Delete</a>
                <a href="@Url.Action("Create", "Program", new { channelId = item.ChannelId })" class="btn btn-warning">Add Program</a>
            </td>
        </tr>
    }
</table>
<h6>Create New Channel</h6>
<a href="/channel/create" class="btn btn-success">Create</a>